- name: "unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: start app
  become: yes
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start